#!/usr/bin/env python3
"""Generate font_rom.v (8x8 ASCII 0x20-0x7E) from font8x8_basic.h (public domain).

The header stores each glyph as 8 bytes, one per row, LSB = leftmost pixel.
"""
import re
import sys

src = open(sys.argv[1]).read()
out = sys.argv[2] if len(sys.argv) > 2 else "font_rom.v"

# parse the 128 rows of "{0x.., 0x.., ...}," in order (chars 0x00-0x7F)
glyphs = re.findall(r"\{\s*((?:0x[0-9A-Fa-f]{2}\s*,\s*){7}0x[0-9A-Fa-f]{2})\s*\}", src)
assert len(glyphs) == 128, len(glyphs)

lines = []
lines.append("// Generated by tools/make_font_rom.py from font8x8_basic.h (public domain)")
lines.append("// 8x8 font, ASCII 0x20-0x7E. bits[0] = leftmost pixel of the row.")
lines.append("`default_nettype none")
lines.append("module font_rom (")
lines.append("    input  wire       clk,")
lines.append("    input  wire [6:0] char,   // ASCII code (0x20-0x7E useful)")
lines.append("    input  wire [2:0] row,")
lines.append("    output reg  [7:0] bits")
lines.append(");")
lines.append("always @(posedge clk) begin")
lines.append("    case ({char, row})")
for code in range(0x20, 0x7F):
    rows = [int(x, 16) for x in re.split(r"\s*,\s*", glyphs[code])]
    for r, v in enumerate(rows):
        if v:
            lines.append(f"        {{7'h{code:02X}, 3'd{r}}}: bits <= 8'h{v:02X};")
lines.append("        default: bits <= 8'h00;")
lines.append("    endcase")
lines.append("end")
lines.append("endmodule")
open(out, "w").write("\n".join(lines) + "\n")
print(f"wrote {out}")
